### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by jisamcom** [yangparing/yangpa#2]
버젼업 하고 나서 Minimap button 을 없애려고 옵션에만 가면 저 에러가 뜨네요.
구 버젼 Lua Setting file 을 WTF 폴더에서 지우고도 해봤는데 마찬가지 입니다. = ) 

1 번
1x Yangpa_Option\Menus\Basic.lua:58: attempt to index field 'minimapButton' (a nil value)
Yangpa_Option\Menus\Basic.lua:58: in function <Yangpa_Option\Menus\Basic.lua:58>
(tail call): ?
(tail call): ?
..._Option\libs\LibHoneyOption-1.0-5\widgets\CheckBox.lua:15: in function <..._Option\libs\LibHoneyOption-1.0\widgets\CheckBox.lua:13>

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'minimapButton' (a nil value)"

2 번
5x Yangpa_Option\Menus\Basic.lua:57: attempt to index field 'minimapButton' (a nil value)
Yangpa_Option\Menus\Basic.lua:57: in function <Yangpa_Option\Menus\Basic.lua:57>
(tail call): ?
...ption\libs\LibHoneyOption-1.0\LibHoneyOption-1.0-5.lua:111: in function <...ption\libs\LibHoneyOption-1.0\LibHoneyOption-1.0.lua:97>
...ption\libs\LibHoneyOption-1.0\LibHoneyOption-1.0-5.lua:129: in function `Update'
...ption\libs\LibHoneyOption-1.0\LibHoneyOption-1.0-5.lua:147: in function <...ption\libs\LibHoneyOption-1.0\LibHoneyOption-1.0.lua:146>
[C]: in function `Show'
FrameXML\InterfaceOptionsFrame.lua:28: in function `InterfaceOptionsList_DisplayPanel'
FrameXML\InterfaceOptionsFrame.lua:46: in function `InterfaceOptionsListButton_OnClick'
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'minimapButton' (a nil value)"

3번
27x Yangpa_Option\Menus\Basic.lua:48: attempt to index field 'minimapButton' (a nil value)
Yangpa_Option\Menus\Basic.lua:48: in function <Yangpa_Option\Menus\Basic.lua:48>
(tail call): ?
(tail call): ?
..._Option\libs\LibHoneyOption-1.0-5\widgets\CheckBox.lua:15: in function <..._Option\libs\LibHoneyOption-1.0\widgets\CheckBox.lua:13>

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'minimapButton' (a nil value)"

**Comment by yangparing** [comment]
r456 버전에서 해당 문제를 수정하였습니다. 구 버전에서 신 버전으로 업데이트할 때 프로필이 한 번 초기화 될 것입니다. 이후 정상적인 사용이 가능합니다.

**Comment by jisamcom** [comment]
수정되었습니다. 감사합니다 = )
